server {

    listen 80;

    server_name localhost;

    root /var/www/demo;

    index index.html;


    # Static files
    location ~* \.(js|css|png|jpg|jpeg|svg|ico|json|woff|woff2|ttf)$ {
        try_files $uri =404;
    }


    # Cartique routes
    location / {

        try_files $uri $uri/ /storefront/demo/full-demo/index.html;

    }

}
